// Code generated by templ - DO NOT EDIT.

package ui

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func AssignLocation(url string) templ.ComponentScript {
	return templ.ComponentScript{
		Name: `__templ_AssignLocation_18fe`,
		Function: `function __templ_AssignLocation_18fe(url){window.location.assign(url)
}`,
		Call:       templ.SafeScript(`__templ_AssignLocation_18fe`, url),
		CallInline: templ.SafeScriptInline(`__templ_AssignLocation_18fe`, url),
	}
}

var _ = templruntime.GeneratedTemplate
